version: "3.8"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: develop
    command: ["--host", "0.0.0.0", "app.main:app", "--reload"]
    environment:
      - LOG_LEVEL=debug
    ports:
    - "8000:8000"
    restart: on-failure
    volumes:
    - ./app:/app/app